### ISSUE TITLE
[BUG]: No publishable resources for tag [lang] - No publishable resources for tag [config]

### ISSUE THREAD

**Issue by sepisoltani** [evryn/laravel-toman#22]
Hi @AmirrezaNasiri 
Thanks for the great package.

Artisan commands in the documentation cannot publish config and lang file.
I will fix the documentation and then request a PR.

Thanks

**Comment by AmirrezaNasiri** [comment]
Hi Sepehr :)
Thank you for caring about the package. I've merged your PR.
