### ISSUE TITLE
[Help] `orderId` does not exist

### ISSUE THREAD

**Issue by ehsan-ej** [evryn/laravel-toman#25]
hi thanks for your package
when try to create request
show this error
Method Evryn\LaravelToman\PendingRequest::orderId does not exist. 
?

**Comment by AmirrezaNasiri** [comment]
Hi @ehsan-ej :)
This method is only available for IDPay gateway. If you're using Zarinpal, you don't need it.

**Comment by ehsan-ej** [comment]
No
I use IDPAY

**Comment by ehsan-ej** [comment]
i can fix that tnx for helping
but in redirect 
i have this error
im using laravel with vu
in comtrrole use requesy->pay
in fronted : 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://idpay.ir/p/ws-sandbox/**************. (Reason: CORS request did not succeed). Status code: (null)

**Comment by AmirrezaNasiri** [comment]
Awesome.
You need to send the redirection URL to the frontend and use JS to redirect the user to the payment gateway.
Since `$request->pay()` returns a `RedirectResponse` object, you can simply get the link using `$request->pay()->getTargetUrl()`.

**Comment by ehsan-ej** [comment]
Thanks!

**Comment by ehsan-ej** [comment]
Is it possible to have a way to connect with each other?
i have some question  and issue in use package 
I'm a novice
Thanks

**Comment by AmirrezaNasiri** [comment]
I might be not available to give technical support about the package. However, you can use [the discussions](https://github.com/evryn/laravel-toman/discussions) section as I check them periodically.
