### ISSUE TITLE
[BUG] support laravel 9

### ISSUE THREAD

**Issue by sajadsoft1** [evryn/laravel-toman#32]
Problem 1
- illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.1) does not satisfy that requirement.
- illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.1) does not satisfy that requirement.
- Root composer.json requires evryn/laravel-toman ^2.0 -> satisfiable by evryn/laravel-toman[v2.0.0, v2.0.1, 2.x-dev].
- Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.0-beta.5 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.0 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.1 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.2 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.1.0 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.2.0 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.3.0 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.3.1 (conflict analysis result)
- Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
- evryn/laravel-toman[v2.0.0, ..., 2.x-dev] require illuminate/support ^7.0|^8.0 -> satisfiable by illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
- Only one of these can be installed: illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate
/support and thus cannot coexist with it.
- Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

**Comment by Bash-So** [comment]
Khodeton ye fork az in package begirid va tooye composer.json requirement esho versionesho bardarid

**Comment by Masihgh** [comment]
pls fix that :)

**Comment by Bash-So** [comment]
> pls fix that :)

Check out my laravel-toman repositofy
 ye fork az hamine ke fix shode bara laravel 9

**Comment by Masihgh** [comment]
> > pls fix that :)
> 
> Check out my laravel-toman repositofy ye fork az hamine ke fix shode bara laravel 9

i'm very nob to use composer :|
how ican add repo as autoload?

**Comment by Bash-So** [comment]
Just use this command in your laravel main folder
`composer require shahrooz/payment`

**Comment by AmirrezaNasiri** [comment]
Sorry for very late delay. Laravel 9.* was supported for a while after this issue but I missed to make it resolved. Laravel 10.* is also supported in Toman v3.
